### login User Request ###

### login User Request ###
POST http://localhost:3333/api/login
Content-Type: application/json

{
  "email": "testuser2@user.com",
  "password": "testpassword"
}

### Register User Response ###
HTTP/1.1 200 OK
Content-Type: application/json

{
  "message": "User logged successfully"
}
