POST http://localhost:3333/api/events
Content-Type: application/json
Authorization: Bearer NQ.amv10ydFqCYu3KpDOZrLYecvjGv62CBn1OCfy_XcXuWIZX9lDbhEUucsTv-y

{
  "title": "event1",
  "description": "test",
  "image": "https://via.placeholder.com/150",
  "date": "2021-01-01T00:00:00",
  "time": "2021-01-01T00:00:00",
  "location": "Event 1 location",
  "userId": 2
}

```


