PUT http://localhost:3333/api/events/1
Content-Type: application/json
Authorization: Bearer Nw.lUuFW6yuMWmdhP3kfRJosp4xW9_Bu7SHu4toK8ZmeoAVZnpq7wI5xfD_T0h-

{
  "title": "My Event UPDATED",
  "description": "This is a test event",
  "image": "https://via.placeholder.com/150",
  "date": "31-12-2023",
  "time": "23:59",
  "location": "Test Location",
  "userId": 1
}
